import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { PrismaClient } from '@prisma/client'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const incrementNuke = () => fetch('/api/add');
  const resetNuke = () => fetch('/api/reset');

  return (
    <>
      <Head>
        <title>Nukes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={incrementNuke}>Add Nuke</button>
        <button onClick={resetNuke}>Remove Nuke</button>
      </main>
    </>
  )
}
